resource "files_remote_server" "example_remote_server" {
  reset_authentication                          = false
  allow_relative_paths                          = true
  aws_access_key                                = "example"
  azure_blob_storage_account                    = "storage-account-name"
  azure_blob_storage_container                  = "container-name"
  azure_blob_storage_dns_suffix                 = "usgovcloudapi.net"
  azure_blob_storage_hierarchical_namespace     = true
  azure_files_storage_account                   = "storage-account-name"
  azure_files_storage_dns_suffix                = "file.core.windows.net"
  azure_files_storage_share_name                = "share-name"
  backblaze_b2_bucket                           = "my-bucket"
  backblaze_b2_s3_endpoint                      = "s3.us-west-001.backblazeb2.com"
  buffer_uploads                                = "example"
  cloudflare_access_key                         = "example"
  cloudflare_bucket                             = "my-bucket"
  cloudflare_endpoint                           = "https://<ACCOUNT_ID>.r2.cloudflarestorage.com"
  description                                   = "More information or notes about my server"
  dropbox_teams                                 = true
  enable_dedicated_ips                          = true
  filebase_access_key                           = "example"
  filebase_bucket                               = "my-bucket"
  files_agent_permission_set                    = "read_write"
  files_agent_root                              = "example"
  files_agent_version                           = "example"
  outbound_agent_id                             = 1
  google_cloud_storage_bucket                   = "my-bucket"
  google_cloud_storage_project_id               = "my-project"
  google_cloud_storage_s3_compatible_access_key = "example"
  hostname                                      = "remote-server.com"
  linode_access_key                             = "example"
  linode_bucket                                 = "my-bucket"
  linode_region                                 = "us-east-1"
  max_connections                               = 1
  name                                          = "My Remote server"
  one_drive_account_type                        = "personal"
  pin_to_site_region                            = true
  port                                          = 1
  upload_staging_path                           = "/tmp/uploads"
  remote_server_credential_id                   = 1
  s3_bucket                                     = "my-bucket"
  s3_compatible_access_key                      = "example"
  s3_compatible_bucket                          = "my-bucket"
  s3_compatible_endpoint                        = "mys3platform.com"
  s3_compatible_region                          = "us-east-1"
  s3_region                                     = "us-east-1"
  server_certificate                            = "require_match"
  server_host_key                               = "[public key]"
  server_type                                   = "s3"
  ssl                                           = "if_available"
  username                                      = "user"
  wasabi_access_key                             = "example"
  wasabi_bucket                                 = "my-bucket"
  wasabi_region                                 = "us-west-1"
  workspace_id                                  = 0
}

