resource "files_remote_server" "example_remote_server" {
  aws_access_key                            = "example"
  wasabi_access_key                         = "example"
  reset_authentication                      = true
  hostname                                  = "remote-server.com"
  name                                      = "My Remote server"
  max_connections                           = 1
  pin_to_site_region                        = true
  port                                      = 1
  s3_bucket                                 = "my-bucket"
  s3_region                                 = "us-east-1"
  server_certificate                        = "require_match"
  server_host_key                           = "[public key]"
  server_type                               = "s3"
  ssl                                       = "if_available"
  username                                  = "user"
  google_cloud_storage_bucket               = "my-bucket"
  google_cloud_storage_project_id           = "my-project"
  backblaze_b2_bucket                       = "my-bucket"
  backblaze_b2_s3_endpoint                  = "s3.us-west-001.backblazeb2.com"
  wasabi_bucket                             = "my-bucket"
  wasabi_region                             = "us-west-1"
  rackspace_username                        = "rackspaceuser"
  rackspace_region                          = "dfw"
  rackspace_container                       = "my-container"
  one_drive_account_type                    = "personal"
  azure_blob_storage_account                = "storage-account-name"
  azure_blob_storage_container              = "container-name"
  azure_blob_storage_hierarchical_namespace = true
  azure_files_storage_account               = "storage-account-name"
  azure_files_storage_share_name            = "share-name"
  s3_compatible_bucket                      = "my-bucket"
  s3_compatible_endpoint                    = "mys3platform.com"
  s3_compatible_region                      = "us-east-1"
  enable_dedicated_ips                      = true
  s3_compatible_access_key                  = "example"
  files_agent_root                          = "example"
  files_agent_permission_set                = "read_write"
  files_agent_version                       = "example"
  filebase_access_key                       = "example"
  filebase_bucket                           = "my-bucket"
  cloudflare_access_key                     = "example"
  cloudflare_bucket                         = "my-bucket"
  cloudflare_endpoint                       = "https://<ACCOUNT_ID>.r2.cloudflarestorage.com"
  dropbox_teams                             = true
  linode_access_key                         = "example"
  linode_bucket                             = "my-bucket"
  linode_region                             = "us-east-1"
}

