resource "files_user" "example_user" {
  avatar_delete                = false
  email                        = "john.doe@files.com"
  group_id                     = 1
  group_ids                    = "example"
  announcements_read           = false
  allowed_ips                  = "10.0.0.0/8\n127.0.0.1"
  attachments_permission       = true
  authenticate_until           = "2000-01-01T01:00:00Z"
  authentication_method        = "password"
  billing_permission           = false
  bypass_user_lifecycle_rules  = false
  bypass_site_allowed_ips      = false
  dav_permission               = true
  disabled                     = true
  filesystem_layout            = "site_root"
  ftp_permission               = true
  header_text                  = "User-specific message."
  language                     = "en"
  notification_daily_send_time = 18
  name                         = "John Doe"
  company                      = "ACME Corp."
  notes                        = "Internal notes on this user."
  office_integration_enabled   = true
  partner_admin                = true
  partner_id                   = 1
  password_validity_days       = 1
  readonly_site_admin          = true
  receive_admin_alerts         = true
  require_login_by             = "2000-01-01T01:00:00Z"
  require_password_change      = true
  restapi_permission           = true
  self_managed                 = true
  sftp_permission              = true
  site_admin                   = true
  skip_welcome_screen          = true
  ssl_required                 = "always_require"
  sso_strategy_id              = 1
  subscribe_to_newsletter      = true
  require_2fa                  = "always_require"
  tags                         = "example"
  time_zone                    = "Pacific Time (US & Canada)"
  user_root                    = "example"
  user_home                    = "example"
  username                     = "user"
  workspace_id                 = 1
}

